# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Traefik installation tasks
  when: traefik_enabled | bool
  tags:
    - setup-all
    - setup-traefik
    - install-all
    - install-traefik
  block:
    - name: Validate Traefik configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Traefik
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Traefik uninstallation tasks
  when: not traefik_enabled | bool
  tags:
    - setup-all
    - setup-traefik
  block:
    - name: Uninstall Traefik
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
