# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Traefik systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ traefik_identifier }}.service"
  register: traefik_service_stat

- name: Uninstall Traefik systemd services and files
  when: traefik_service_stat.stat.exists | bool
  block:
    - name: Ensure Traefik systemd service is stopped
      ansible.builtin.systemd:
        name: "{{ traefik_identifier }}"
        state: stopped
        daemon_reload: true

    - name: Ensure Traefik systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ traefik_identifier }}.service"
        state: absent

    - name: Ensure Traefik container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ traefik_container_network }}"
        state: absent

    - name: Ensure Traefik container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ traefik_container_network }}
      register: network_deletion_result
      changed_when: traefik_container_network in network_deletion_result.stdout

    - name: Remove Traefik path does not exist
      ansible.builtin.file:
        path: "{{ traefik_base_path }}"
        state: absent
